apiVersion: v1
kind: Pod
metadata:
  name: time-check
  namespace: devops
  labels:
    env: production
spec:
  containers:
  - name: time-check
    image: busybox:latest
    volumeMounts:
    - name: log-volume
      mountPath: /opt/itadmin/time
    env:
    - name: TIME_FREQ
      valueFrom:
        configMapKeyRef:
          name: time-config
          key: TIME_FREQ
    command: ["/bin/sh", "-c"]
    args:
      - |
        while true;
        do date >> /opt/itadmin/time/time-check.log;
        sleep $(TIME_FREQ);
        done
  volumes:
  - name: log-volume
    emptyDir: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: time-config
  namespace: devops
data:
  TIME_FREQ: "12"